# Generated by Django 4.2 on 2023-04-27 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('symbol', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('short_name', models.TextField(blank=True, null=True)),
                ('long_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Crypto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('symbol', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('short_name', models.TextField(blank=True, null=True)),
                ('long_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Stocks',
                'managed': False,
            },
        ),
    ]
